name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test_front:
    name: test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - run: npm test
  coverage:
    needs: [ test_front ]
    name: coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
