name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test_front:
    name: test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: cd frontend
      - run: npm install
      - run: npm run build
      - run: npm test
  coverage:
    needs: [ test_front ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: cd frontend
      - run: npm install
      - run: npm run build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 8ca44da13bfaf12d967b12200f52ab0e978c6f5a80b4f8a205e33d3d9a30dfd4
        with:
          coverageCommand: npm run coverage
